INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Make-up', 1, ',1,', ',', ',Make-up,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Aprons', 1, ',1,', ',', ',Aprons,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Handheld', 1, ',1,', ',', ',Handheld,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('head_other', 1, ',1,', ',', ',head_other,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Accessories (belts etc.)', 1, ',1,', ',', ',Accessories (belts etc.),All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('', 1, ',1,', ',', ',,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Tights', 1, ',1,', ',', ',Tights,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Mask', 1, ',1,', ',', ',Mask,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Glasses', 1, ',1,', ',', ',Glasses,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Prosthetics ', 1, ',1,', ',', ',Prosthetics ,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Outer wear (coats etc.)', 1, ',1,', ',', ',Outer wear (coats etc.),All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Writing', 1, ',1,', ',', ',Writing,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Gloves', 1, ',1,', ',', ',Gloves,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('All', 1, ',1,', ',', ',All,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Stationary/office', 1, ',1,', ',', ',Stationary/office,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('electronics ', 1, ',1,', ',', ',electronics ,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Other', 1, ',1,', ',', ',Other,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('animals', 1, ',1,', ',', ',animals,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Army', 1, ',1,', ',', ',Army,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Arms/hands', 1, ',1,', ',', ',Arms/hands,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Large cloths', 1, ',1,', ',', ',Large cloths,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Tableware', 1, ',1,', ',', ',Tableware,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Lighting', 1, ',1,', ',', ',Lighting,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Wig', 1, ',1,', ',', ',Wig,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Melee', 1, ',1,', ',', ',Melee,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Gun', 1, ',1,', ',', ',Gun,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Bladed', 1, ',1,', ',', ',Bladed,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Floral', 1, ',1,', ',', ',Floral,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Household', 1, ',1,', ',', ',Household,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('top_Other', 1, ',1,', ',', ',top_Other,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Bags, Suitcases and Containers ', 1, ',1,', ',', ',Bags, Suitcases and Containers ,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Cup/glass/bottle', 1, ',1,', ',', ',Cup/glass/bottle,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Pots and Pans', 1, ',1,', ',', ',Pots and Pans,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Shoes', 1, ',1,', ',', ',Shoes,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Glass', 1, ',1,', ',', ',Glass,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Cutlery', 1, ',1,', ',', ',Cutlery,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Plate', 1, ',1,', ',', ',Plate,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Hat', 1, ',1,', ',', ',Hat,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Food trays', 1, ',1,', ',', ',Food trays,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Food (fake)', 1, ',1,', ',', ',Food (fake),All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Top', 1, ',1,', ',', ',Top,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Tools', 1, ',1,', ',', ',Tools,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Archive', 1, ',1,', ',', ',Archive,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Materials ', 1, ',1,', ',', ',Materials ,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Board stuff', 1, ',1,', ',', ',Board stuff,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Long', 1, ',1,', ',', ',Long,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Bow', 1, ',1,', ',', ',Bow,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Weapon', 1, ',1,', ',', ',Weapon,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Chairs', 1, ',1,', ',', ',Chairs,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Dress', 1, ',1,', ',', ',Dress,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Items', 1, ',1,', ',', ',Items,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('pillows', 1, ',1,', ',', ',pillows,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('blankets', 1, ',1,', ',', ',blankets,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Corset', 1, ',1,', ',', ',Corset,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Trousers', 1, ',1,', ',', ',Trousers,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Shorts', 1, ',1,', ',', ',Shorts,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Paint', 1, ',1,', ',', ',Paint,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Paint-like', 1, ',1,', ',', ',Paint-like,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Paint Rollers', 1, ',1,', ',', ',Paint Rollers,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Painting clothes', 1, ',1,', ',', ',Painting clothes,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Measuring', 1, ',1,', ',', ',Measuring,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('other tools', 1, ',1,', ',', ',other tools,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Tarps', 1, ',1,', ',', ',Tarps,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Paper', 1, ',1,', ',', ',Paper,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Beads', 1, ',1,', ',', ',Beads,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Cufflinks', 1, ',1,', ',', ',Cufflinks,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Buttons', 1, ',1,', ',', ',Buttons,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Shiny stuff', 1, ',1,', ',', ',Shiny stuff,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Cleaning materials', 1, ',1,', ',', ',Cleaning materials,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Electric', 1, ',1,', ',', ',Electric,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Pins and Staples', 1, ',1,', ',', ',Pins and Staples,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('other materials ', 1, ',1,', ',', ',other materials ,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Wood', 1, ',1,', ',', ',Wood,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Fabric', 1, ',1,', ',', ',Fabric,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Beverages', 1, ',1,', ',', ',Beverages,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Brushes', 1, ',1,', ',', ',Brushes,All,');
INSERT INTO wp_rordbv2_cat (name, parentid, parentid_list, childid_list, searchtags) VALUES ('Jacket', 1, ',1,', ',', ',Jacket,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('38 - Make-up drawer 1 - Make-up base', 1, ',1,', ',', ',38 - Make-up drawer 1 - Make-up base,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('1 - Profession specific props', 1, ',1,', ',', ',1 - Profession specific props,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('2 - below the waist accessories', 1, ',1,', ',', ',2 - below the waist accessories,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('', 1, ',1,', ',', ',,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('All', 1, ',1,', ',', ',All,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('3 - face accessories', 1, ',1,', ',', ',3 - face accessories,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('4 - Neck accessories', 1, ',1,', ',', ',4 - Neck accessories,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('6 - Writing tools', 1, ',1,', ',', ',6 - Writing tools,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('5 - Arm accessories', 1, ',1,', ',', ',5 - Arm accessories,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('21 - Electronic props', 1, ',1,', ',', ',21 - Electronic props,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('32 - Misc. props', 1, ',1,', ',', ',32 - Misc. props,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('4.2 - Red Scarves', 1, ',1,', ',', ',4.2 - Red Scarves,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('33.1 - Wigs', 1, ',1,', ',', ',33.1 - Wigs,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('33.2 - armor and small weapons', 1, ',1,', ',', ',33.2 - armor and small weapons,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('22 - Flower baskets', 1, ',1,', ',', ',22 - Flower baskets,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('33 - Wigs and Weaponry', 1, ',1,', ',', ',33 - Wigs and Weaponry,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('23.1 - random large stuff', 1, ',1,', ',', ',23.1 - random large stuff,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('35.1 - Books and Notetaking tools', 1, ',1,', ',', ',35.1 - Books and Notetaking tools,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('23.2 - large rectangular stuff', 1, ',1,', ',', ',23.2 - large rectangular stuff,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('24 - suitcases and other containers ', 1, ',1,', ',', ',24 - suitcases and other containers ,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('35.2 - Lighting', 1, ',1,', ',', ',35.2 - Lighting,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('28 - glass and cups', 1, ',1,', ',', ',28 - glass and cups,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('36 - Shoes', 1, ',1,', ',', ',36 - Shoes,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('29 - hats', 1, ',1,', ',', ',29 - hats,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('25.1 - food and cooking', 1, ',1,', ',', ',25.1 - food and cooking,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('25.2 - big floppy, magic, christmas and monstrous hats', 1, ',1,', ',', ',25.2 - big floppy, magic, christmas and monstrous hats,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('34 - Other', 1, ',1,', ',', ',34 - Other,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('12 - Tall items/Corner', 1, ',1,', ',', ',12 - Tall items/Corner,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('0 - Center of the room', 1, ',1,', ',', ',0 - Center of the room,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('under the clothing', 1, ',1,', ',', ',under the clothing,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('13 - materials left top closet', 1, ',1,', ',', ',13 - materials left top closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('14 - materials middle top closet', 1, ',1,', ',', ',14 - materials middle top closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('15 - materials right top closet', 1, ',1,', ',', ',15 - materials right top closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('16 - materials top closet', 1, ',1,', ',', ',16 - materials top closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('19 - materials bottom closet', 1, ',1,', ',', ',19 - materials bottom closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('17 - materials left middle closet', 1, ',1,', ',', ',17 - materials left middle closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('18 - materials right middle closet', 1, ',1,', ',', ',18 - materials right middle closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('8 - 2nd from top board closet', 1, ',1,', ',', ',8 - 2nd from top board closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('9 - middle board closet', 1, ',1,', ',', ',9 - middle board closet,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('55 - ropes', 1, ',1,', ',', ',55 - ropes,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('52 - screwdrivers, pliere, files', 1, ',1,', ',', ',52 - screwdrivers, pliere, files,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('53 - paint brushes', 1, ',1,', ',', ',53 - paint brushes,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('56 - glitter, wooden sticks', 1, ',1,', ',', ',56 - glitter, wooden sticks,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('54 - light bulbs, hinges and metal connection plates', 1, ',1,', ',', ',54 - light bulbs, hinges and metal connection plates,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('51 - toolbox with items like staples', 1, ',1,', ',', ',51 - toolbox with items like staples,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('7 - board closet top', 1, ',1,', ',', ',7 - board closet top,All,');
INSERT INTO wp_rordbv2_loc (name, parentid, parentid_list, childid_list, searchtags) VALUES ('65 - jacket lower', 1, ',1,', ',', ',65 - jacket lower,All,');
